/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PhysiotherapistDocRole;

import Business.Enterprises.Enterprise;
import Business.Network.NetworkSystem;
import Business.Organization.PhysiotherapistOrg;
import Business.UserAccount.User_Account;
import Business.WorkStream.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pranali
 */
public class treatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form treatJPanel
     */
   

    JPanel userProcessContainer;
    User_Account userAccount;
    PhysiotherapistOrg organization;
    Enterprise enterprise;
    NetworkSystem network; 
    WorkRequest request;
    String treatment_methods[] = {"Trauma-Informed Therapy", "Diet, Nutrition , & Wellness Therapy", "Group Therapy", "Individual Therapy","Come for Cognitive Behavioral Therapy"};

    treatJPanel(JPanel userProcessContainer, User_Account userAccount, PhysiotherapistOrg organization, Enterprise enterprise, NetworkSystem network, WorkRequest request) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.userAccount = userAccount;
    this.organization = organization;
    this.enterprise = enterprise;
    this.network = network;
    this.request = request;
    Loadddl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ddlmeetings = new javax.swing.JComboBox();
        btnsenddecision = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Select meeting frequency");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        ddlmeetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlmeetingsActionPerformed(evt);
            }
        });
        jPanel3.add(ddlmeetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 199, -1));

        btnsenddecision.setBackground(new java.awt.Color(255, 255, 204));
        btnsenddecision.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnsenddecision.setText("Send Decision to patient");
        btnsenddecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsenddecisionActionPerformed(evt);
            }
        });
        jPanel3.add(btnsenddecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 60));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 266, 869));

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Pharmacotherapist Work Area");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 0, 1200, 68));
    }// </editor-fold>//GEN-END:initComponents

    private void btnsenddecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsenddecisionActionPerformed
     request.setDiagnose( (String )ddlmeetings.getSelectedItem() + " is recommended by  Phrmacotherapist" );
     JOptionPane.showMessageDialog(null, "Decision sent to patient ");
    }//GEN-LAST:event_btnsenddecisionActionPerformed

    private void ddlmeetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlmeetingsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ddlmeetingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsenddecision;
    private javax.swing.JComboBox ddlmeetings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    private void Loadddl() {
        for(String str: treatment_methods)
       {
           ddlmeetings.addItem(str);
       }
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
