/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorRole;

import Business.Enterprises.Enterprise;
import Business.Enterprises.RehabEnterprises;
import Business.Network.NetworkSystem;
import Business.Organization.DoctorConsultantOrg;
import Business.Organization.Org;
import Business.Organization.PhysiotherapistOrg;
import Business.Organization.PsychiatristOrg;
import Business.UserAccount.User_Account;
import Business.WorkStream.WorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.sun.jdi.connect.Transport;
import java.io.FileOutputStream;
import java.net.PasswordAuthentication;
import javax.swing.text.Document;
/**
 *
 * @author Makarand
 */
public class ViewLabResultcases extends javax.swing.JPanel {

    JPanel userProcessContainer;
    WorkRequest patientrequest;
    NetworkSystem network;
    Enterprise enterprise;
    User_Account userAccount;

     String emailId=null;
    /**
     * Creates new form ViewLabResultcases
     */
    public ViewLabResultcases(JPanel userProcessContainer, WorkRequest request, NetworkSystem network, Enterprise enterprise, User_Account userAccount) {
        initComponents();
        this.patientrequest = request;
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        popupResult();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txt = new javax.swing.JTextField();
        txtResultType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtResultbyLab = new javax.swing.JTextField();
        btnPsyc = new javax.swing.JButton();
        btnphrmaco = new javax.swing.JButton();
        btnPrescription = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lab Process Result");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(639, 639, 639)
                .addComponent(jLabel7)
                .addContainerGap(1055, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setText("Result");

        jLabel4.setText("Result Type");

        jLabel5.setText("Name");

        txtName.setBackground(new java.awt.Color(153, 204, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txt.setBackground(new java.awt.Color(153, 204, 255));

        txtResultType.setBackground(new java.awt.Color(153, 204, 255));
        txtResultType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultTypeActionPerformed(evt);
            }
        });

        jLabel6.setText("Solution By Lab");

        txtResultbyLab.setBackground(new java.awt.Color(153, 204, 255));

        btnPsyc.setBackground(new java.awt.Color(153, 204, 255));
        btnPsyc.setText("Send To Psychiatrist");
        btnPsyc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsycActionPerformed(evt);
            }
        });

        btnphrmaco.setBackground(new java.awt.Color(153, 204, 255));
        btnphrmaco.setText("Send To Pharmacotherapist");
        btnphrmaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphrmacoActionPerformed(evt);
            }
        });

        btnPrescription.setBackground(new java.awt.Color(153, 204, 255));
        btnPrescription.setText("Write Prescription");
        btnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel5)
                .addContainerGap(678, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(btnPsyc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(txtResultType)
                            .addComponent(txtResultbyLab))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnphrmaco)
                            .addGap(18, 18, 18)
                            .addComponent(btnPrescription)))
                    .addContainerGap(283, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addContainerGap(477, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(63, 63, 63)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtResultType, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel4)))
                    .addGap(38, 38, 38)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtResultbyLab, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(45, 45, 45)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPsyc)
                        .addComponent(btnphrmaco)
                        .addComponent(btnPrescription))
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_button.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(717, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1920, 980));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtResultTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultTypeActionPerformed

    private void btnPsycActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPsycActionPerformed
        // TODO add your handling code here:
        Org org = null;
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof RehabEnterprises) {
                for (Org organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof PsychiatristOrg) {
                        org = organization;
                        break;
                    }
                }
            }
        }
        if (org != null) {
            //int a =org.getWorkQueue().getWorkRequestList().hashCode();
            org.getWorkStream().getWorkRequestList().add(patientrequest);
            patientrequest.setReceiver(null);
            userAccount.getWorkQueue().getWorkRequestList().add(patientrequest);
        }
        patientrequest.setStatus("Assigned to psychiatrist");
         JOptionPane.showMessageDialog(null, "Request sent to psychiatrist");
          popupResult();
    }//GEN-LAST:event_btnPsycActionPerformed

    private void btnphrmacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphrmacoActionPerformed
        // TODO add your handling code here:
        System.out.println("aaa");
// emailId = "kunwar.chopra@gmail.com";
//
// String emailRegex = "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$";
//
// Pattern pat = Pattern.compile(emailRegex);
// if (emailId == null)
// {
// JOptionPane.showMessageDialog(null, "Please enter a valid email id. It should not start with _ and must contain an email Id with _, . and @ only!!");
// return;
// }
//
// else
// {
// if(!(pat.matcher(emailId).matches()) )
// {
// JOptionPane.showMessageDialog(null, "Please enter a valid email id. It should not start with _ and must contain an email Id with _, . and @ !!");
// return;
// }
//
// }
//
// if(emailId.equalsIgnoreCase(""))
// {
// JOptionPane.showMessageDialog(null, "Please enter an email id before buying the product");
// return;
// }
//
// sendMail(emailId);
// //Email Sending part
//
//
// //pdf part
        //pdf part
        Document document = new Document();
     
        //pdf part
        Org org = null;
     for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
          if (enterprise instanceof RehabEnterprises){     
        for (Org organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PhysiotherapistOrg){
                org = organization;               
                     
            } 
          }
        }      
     }   
     if(org!=null)
     {
      org.getWorkStream().getWorkRequestList().add(patientrequest);
            patientrequest.setReceiver(null);
            userAccount.getWorkQueue().getWorkRequestList().add(patientrequest);
     }
     JOptionPane.showMessageDialog(null, "Requested to Pharmacotherapist");
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnphrmacoActionPerformed

    public void sendMail(String emailId)
    {
    final String username = "bookmymovie13@gmail.com";
		final String password = "ijklmn786@";

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props,
		  new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		  });

		try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("sojitradharti15@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse(emailId));
			message.setSubject("pharmacotherapist Request");
			message.setText("pharmacotherapist Request sent successfuly.");

			Transport.send(message);

			//System.out.println("Done");

		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
                 patientrequest.setStatus("Assigned to pharmacotherapist");
                 popupResult();
	}
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescriptionActionPerformed
        // TODO add your handling code here:
        RequestDruggistForMedicineJPanel medPanel = new RequestDruggistForMedicineJPanel(userProcessContainer, patientrequest, network, userAccount,  enterprise);
        
       
            userProcessContainer.add("processWorkRequestJPanel", medPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();

            layout.next(userProcessContainer);
            JOptionPane.showMessageDialog(null, "Request sent back to Doctor");
            popupResult();
    }//GEN-LAST:event_btnPrescriptionActionPerformed


    private void popupResult() {
        
        txtName.setText(patientrequest.getSender().getUsername());
        txt.setText(patientrequest.getLabresult());
        txtResultType.setText(patientrequest.getResulttype());
        txtResultbyLab.setText(patientrequest.getSolution());
        String category = txtResultType.getText();
           if(category.contains("Pharmacotherapist"))
           {
               btnPsyc.setEnabled(false);
               btnPrescription.setEnabled(false);
           }
           else if(category.contains("Psychiatrist"))
           {
               btnphrmaco.setEnabled(false);
               btnPrescription.setEnabled(false);
           }
           else if(category.contains("Not Overdose"))
           {
               btnphrmaco.setEnabled(false);
               btnPsyc.setEnabled(false);
           }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrescription;
    private javax.swing.JButton btnPsyc;
    private javax.swing.JButton btnphrmaco;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtResultType;
    private javax.swing.JTextField txtResultbyLab;
    // End of variables declaration//GEN-END:variables
}
