/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MedicalCampOrganizerRole;

import Business.Ecosystem.Ecosystem;
import UI.CSRManagerRole.RequestDoctorForMedCampJPanel;
import Business.Enterprises.Enterprise;
import Business.Network.NetworkSystem;
import Business.Organization.Org;
import Business.UserAccount.User_Account;
import Business.WorkStream.HosMedCampWorkRequest;
import Business.WorkStream.MedicalCampRequest;
import Business.WorkStream.MedicalCampWorkRequest;
import Business.WorkStream.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranali
 */
public class MedicalCampOrganizerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalCampOrganizerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Org organization;
    private Enterprise enterprise;
    private User_Account userAccount;
    private Ecosystem business;
    private NetworkSystem network;
    
     public MedicalCampOrganizerWorkAreaJPanel(JPanel userProcessContainer, User_Account account, Org organization, Enterprise enterprise, Ecosystem business, NetworkSystem network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.network = network;
        populateTableReqFromVol();
    }
     
    public void populateTableReqFromVol(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        model.setRowCount(0);
        //System.out.print(userAccount.getWorkQueue1().getWorkRequestList());
        for (WorkRequest request : userAccount.getWorkStream().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSender();
            row[2] = request.getReceiver();
            row[3] = request.getStatus();
            String result = ((MedicalCampWorkRequest) request).getCampResult();
            row[4] = result == null ? "Waiting" : result;
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestCampJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Medical Camp Organizer Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 247, -1, 160));

        requestCampJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestCampJButton.setText("Raise New Medical Camp Request");
        requestCampJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestCampJButtonActionPerformed(evt);
            }
        });
        add(requestCampJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, 31));

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Assigned To", "Status", "Camp Result"
            }
        ));
        jScrollPane2.setViewportView(workRequestJTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 511, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/camp1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestCampJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestCampJButtonActionPerformed
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestMedicalCampsJPanel", new RequestMedicalCampjPanel(userProcessContainer, userAccount, enterprise, business, network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestCampJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton requestCampJButton;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
