/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MedicalCampOrganizerRole;

import UI.VolunteerRole.*;
import Business.Ecosystem.Ecosystem;
import Business.Enterprises.Enterprise;
import Business.Enterprises.HospitalEnterprises;
import Business.Enterprises.NGOEnterprise;
import Business.Network.NetworkSystem;
import Business.Organization.CSROrganization;
import Business.Organization.Org;
import Business.Organization.VolunteerOrganization;
import Business.UserAccount.User_Account;
import Business.WorkStream.MedicalCampWorkRequest;
import Business.WorkStream.NgoMedCampWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import UI.CSRManagerRole.CSRManagerWorkAreajPanel;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Pranali
 */
public class RequestMedicalCampjPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestMedicalCampjPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private User_Account userAccount;
    private Ecosystem business;
    private NetworkSystem network;
    boolean emptyValidationStatus = true;
    public RequestMedicalCampjPanel(JPanel userProcessContainer, User_Account userAccount, Enterprise enterprise, Ecosystem business, NetworkSystem network ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        this.network = network;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, 30));

        messageJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 249, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 135, 26));

        requestTestJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestTestJButton.setText("Request Medical Camp");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Request Medical Camp");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 6, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/camp1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        try{
            if(EmpytyFieldValidation()){
                String message = messageJTextField.getText();
        
        if(message.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter text");
            return;
        }
        
        MedicalCampWorkRequest medcampWReq = new MedicalCampWorkRequest();
        medcampWReq.setMessage(message);
        medcampWReq.setSender(userAccount);
        medcampWReq.setStatus("Sent from NGO");
        medcampWReq.setCampResult("Requested");

        Org org = null;
        for(NetworkSystem network: business.getNetworkList()){
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise instanceof HospitalEnterprises){
                    for (Org organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        // raising req to volunteer organization 
                        if (organization instanceof CSROrganization){
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
        if (org!=null){
            // adding req on user account of refugee camp manager
            org.getWorkStream().getWorkRequestList().add(medcampWReq);
            userAccount.getWorkStream().getWorkRequestList().add(medcampWReq);
        }
        messageJTextField.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this,"Request cannot be empty");
                emptyValidationStatus=true;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Request not submitted, Try again");
            System.out.println(e.toString());
            emptyValidationStatus=true;
        }
        
//        String message = messageJTextField.getText();
//        
//        if(message.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Please enter text");
//            return;
//        }
//        
//        MedicalCampWorkRequest medcampWReq = new MedicalCampWorkRequest();
//        medcampWReq.setMessage(message);
//        medcampWReq.setSender(userAccount);
//        medcampWReq.setStatus("Sent from NGO");
//        medcampWReq.setCampResult("Requested");
//
//        Org org = null;
//        for(NetworkSystem network: business.getNetworkList()){
//            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
//                if(enterprise instanceof HospitalEnterprises){
//                    for (Org organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//                        // raising req to volunteer organization 
//                        if (organization instanceof CSROrganization){
//                            org = organization;
//                            break;
//                        }
//                    }
//                }
//            }
//        }
//        if (org!=null){
//            // adding req on user account of refugee camp manager
//            org.getWorkStream().getWorkRequestList().add(medcampWReq);
//            userAccount.getWorkStream().getWorkRequestList().add(medcampWReq);
//        }
//        messageJTextField.setText("");
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // refreshing components when going back page
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MedicalCampOrganizerWorkAreaJPanel mcoqajp = (MedicalCampOrganizerWorkAreaJPanel) component;
        mcoqajp.populateTableReqFromVol();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private boolean EmpytyFieldValidation() {
        if(messageJTextField.getText().equals(null) || messageJTextField.getText().trim().isEmpty() )
        {
            messageJTextField.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            messageJTextField.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!messageJTextField.getText().equals(null) && !messageJTextField.getText().trim().isEmpty() )
        {
            messageJTextField.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        
        return emptyValidationStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
